name: Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework==7.0

    - name: Add Robot Framework to PATH
      run: echo "::add-path::/opt/hostedtoolcache/Python/3.10.12/x64/bin/"

    - name: Run Robot Framework tests
      run: |
        /opt/hostedtoolcache/Python/3.10.12/x64/bin/robot tests/
