name: Robot Framework Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework==7.0
        pip install robotframework-seleniumlibrary

    - name: Install Firefox and GeckoDriver
      run: |
        sudo apt update
        sudo apt install -y firefox
        wget https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.30.0-linux64.tar.gz
        chmod +x geckodriver
        sudo mv geckodriver /usr/local/bin/

    - name: Run Robot Framework tests
      run: |
        robot --variable BROWSER:firefox tests/
