name: Robot Framework Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.10-slim

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y \
          default-jre \
          wget \
          gnupg \
          curl \
          unzip \
          && pip install --upgrade pip \
          && pip install robotframework==7.0 robotframework-seleniumlibrary

    - name: Add Google Chrome repository key
      run: |
        if ! wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -; then
          echo "Failed to add Google Chrome repository key"
          exit 1
        fi

    - name: Add Google Chrome repository
      run: |
        echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list

    - name: Install Google Chrome
      run: |
        if ! apt-get update && apt-get install -y google-chrome-stable; then
          echo "Failed to install Google Chrome"
          exit 1
        fi

    - name: Download and install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d '.' -f 1)
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        if [ -z "$CHROMEDRIVER_VERSION" ]; then
          echo "Failed to fetch ChromeDriver version."
          exit 1
        fi
        if ! wget -q -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip; then
          echo "Failed to download ChromeDriver."
          exit 1
        fi
        if ! unzip -qq /tmp/chromedriver_linux64.zip -d /tmp; then
          echo "Failed to unzip ChromeDriver."
          exit 1
        fi
        chmod +x /tmp/chromedriver
        if ! mv /tmp/chromedriver /usr/local/bin/; then
          echo "Failed to move ChromeDriver."
          exit 1
        fi

    - name: Run Robot Framework tests
      run: robot --variable BROWSER:headlesschrome tests/
