name: Acceptance Tests

on:
  push:
    branches:
      - master

jobs:
  web_testing_in_chrome:
    runs-on: ubuntu-latest
    container:
      image: fedora:31
    steps:
      - name: Check Fedora version
        run: cat /etc/*-release
      - name: Upgrade Fedora
        run: sudo dnf upgrade -y
      - name: Install Dependencies
        run: |
          sudo dnf install -y \
            python37 \
            fedora-workstation-repositories \
            dnf-plugins-core
          sudo dnf config-manager --set-enabled google-chrome
          sudo dnf install -y google-chrome-stable
          pip3 install --upgrade pip
          pip3 install webdrivermanager robotframework robotframework-seleniumlibrary
          webdrivermanager chrome
      - name: Verify installations
        run: |
          python3 --version
          google-chrome --version
          chromedriver --version
      - name: Run Tests
        run: robot -d ./results -v BROWSER:headlesschrome -d ./tests/tc01.robot
      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: ./results
    env:
      CHROME_BIN: /usr/bin/google-chrome
      CHROMEDRIVER_PATH: /usr/bin/chromedriver
