name: Robot Framework Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.10-slim

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y \
          default-jre \
          wget \
          gnupg \
          curl \
          unzip \
          && pip install --upgrade pip \
          && pip install robotframework==7.0 robotframework-seleniumlibrary

    - name: Add Google Chrome repository key
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -

    - name: Add Google Chrome repository
      run: |
        echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list

    - name: Install Google Chrome
      run: |
        apt-get update && apt-get install -y google-chrome-stable

    - name: Obtain Chrome version
      run: |
        CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d '.' -f 1)
        if [ -z "$CHROME_VERSION" ]; then
          echo "Failed to obtain Chrome version."
          exit 1
        fi

    - name: Run Robot Framework tests
      run: robot --variable BROWSER:headlesschrome --chrome-binary=/usr/bin/google-chrome tests/
