name: Run Robot Framework Tests

on:
  push:
    branches:
      - master  # Configure as needed
  pull_request:
    branches:
      - master  # Configure as needed

jobs:
  run_tests:
    name: Robot Framework Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Robot Framework Tests
      run: |
        robot -d results/ tests/  # Specify your test directory and output directory

