name: Acceptance Tests

on:
  push:
    branches:
      - master

jobs:
  web_testing_in_chrome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      with:
        node-version: 16
        - name: Install operating system dependencies
        run: |
         npm install -g allure-commandline --save-dev |
         rfbrowser init
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          rfbrowser init
      - name: Run tests
        if: always()
        continue-on-error: true
        run: |
          python -m robot --listener allure_robotframework --variable  HEADLESS_FLAG:True -d my_reports  ./
        env:
          ALLURE_MAX_STEP_MESSAGE_COUNT: 5