name: Robot Framework Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework==7.0
        pip install robotframework-seleniumlibrary

    - name: Install Chrome and ChromeDriver
      run: |
        sudo apt update
        sudo apt install -y chromium-browser chromium-chromedriver

    - name: Debug Information
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of /usr/bin:"
        ls -la /usr/bin
        echo "Contents of /opt:"
        ls -la /opt

    - name: Run Robot Framework tests
      run: |
        export CHROME_BIN=/usr/bin/chromium-browser
        robot --variable BROWSER:headlesschrome --variable webdriver.chrome.driver:/usr/bin/chromedriver tests/
