name: Robot Framework Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.10-slim

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y \
          default-jre \
          wget \
          unzip \
          && pip install --upgrade pip \
          && pip install robotframework==7.0 robotframework-seleniumlibrary

    - name: Download and install Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
        echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
        apt-get update
        apt-get install -y google-chrome-stable

    - name: Download and install ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d '.' -f 1)
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
        wget -q -O /tmp/chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip -qq /tmp/chromedriver_linux64.zip -d /tmp
        chmod +x /tmp/chromedriver
        mv /tmp/chromedriver /usr/local/bin/

    - name: Run Robot Framework tests
      run: robot --variable BROWSER:headlesschrome tests/
