name: Robot Framework Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: python:3.10-slim

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y \
          chromium \
          chromium-driver \
          libglib2.0-0 \
          libnss3 \
          libgconf-2-4 \
          libfontconfig1 \
          default-jre \
          && pip install --upgrade pip \
          && pip install robotframework==7.0 robotframework-seleniumlibrary

    - name: Run Robot Framework tests
      run: robot --variable BROWSER:headlesschrome tests/
