name: Acceptance Tests

on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master

jobs:
  web_testing_in_chrome:
    runs-on: ubuntu-latest
    container:
      image: fedora:31
    env:
      CHROME_BIN: /usr/bin/google-chrome
      CHROMEDRIVER_PATH: /usr/bin/chromedriver
    steps:
      - name: Check Fedora version
        run: cat /etc/*-release
      - name: Upgrade Fedora
        run: sudo dnf upgrade -y
      - name: Install Dependencies
        run: |
          sudo dnf install -y \
          python37 \
          fedora-workstation-repositories \
          dnf-command(config-manager) \
          google-chrome-stable
          pip3 install --upgrade pip
          pip3 install webdrivermanager robotframework robotframework-seleniumlibrary
          webdrivermanager chrome
      - name: Verify installations
        run: |
          python --version
          google-chrome --version
          chromedriver --version
      - name: Run Tests
        run: robot -d ./results -v BROWSER:headlesschrome tc01.robot
      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./results

  web_testing_in_chrome_and_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t mydockerimages .
      - name: Run Tests in Docker
        run: docker run mydockerimages
      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: ./results
