name: Robot Framework Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework==7.0
        pip install robotframework-seleniumlibrary
        pip install webdrivermanager

    - name: Install Chrome and configure ChromeDriver
      run: |
        webdrivermanager chrome --linkpath /usr/local/bin

    - name: Run Robot Framework tests
      run: |
        robot --variable BROWSER:headlesschrome tests/
