name: Acceptance Tests

on:
  push:
    branches:
      - master

jobs:
  web_testing_in_chrome:
    runs-on: ubuntu-latest
    container:
      image: fedora:31
    env:
      CHROME_BIN: /usr/bin/google-chrome
      CHROMEDRIVER_PATH: /usr/bin/chromedriver
    steps:
      - name: Check Fedora version
        run: cat /etc/*-release
      - name: Upgrade Fedora
        run: sudo dnf upgrade -y
      - name: Install Dependencies
        run: |
          sudo dnf install -y \
            python37 \
            google-chrome-stable \
            python3-pip \
            libappindicator \
            libdbusmenu \
            dbus-x11 \
            gtk3 \
            ipa-gothic-fonts \
            ipa-mincho-fonts \
            xorg-x11-fonts-100dpi \
            xorg-x11-fonts-75dpi \
            xorg-x11-utils \
            xorg-x11-fonts-cyrillic \
            xorg-x11-fonts-Type1 \
            xorg-x11-fonts-misc \
            dnf-command(config-manager)
          pip3 install --upgrade pip
          pip3 install webdrivermanager robotframework robotframework-seleniumlibrary
          webdrivermanager chrome
      - name: Verify installations
        run: |
          python3 --version
          google-chrome --version
          chromedriver --version
      - name: Run Tests
        run: robot -d ./results -v BROWSER:headlesschrome ./tests/tc01.robot
      - name: Archive Test Results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: ./results
