name: Robot Framework Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework==7.0
        pip install robotframework-seleniumlibrary

    - name: Remove existing ChromeDriver
      run: |
        sudo rm /usr/local/bin/chromedriver || true

    - name: Determine Chrome version
      run: |
        CHROME_VERSION=$(google-chrome --version | cut -d' ' -f3 | cut -d'.' -f1)
        echo "Detected Chrome version: $CHROME_VERSION"

    - name: Download and install ChromeDriver
      run: |
        if [ "$CHROME_VERSION" = "121" ]; then
          CHROME_DRIVER_VERSION="121.0.6167.184"
        else
          echo "Unsupported Chrome version: $CHROME_VERSION"
          exit 1
        fi
        wget -N "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        chmod +x chromedriver
        sudo mv chromedriver /usr/local/bin/

    - name: Run Robot Framework tests
      run: |
        robot --variable BROWSER:headlesschrome tests/

        